# External plugins
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
plugins:
  - jekyll-archives
  - jekyll-paginate-v2
  - mini_magick

include: ['_pages']
exclude:
  - "/vendor/"
  - "/.idea/"
  - "*.bat"
  - "Gemfile*"
  - "circle.yml"
  - "LICENSE.md"
  - "README.md"
  - "featured.json"
  - "pagefind.exe"
  - "pagefind.yaml"
  - "/docs/"

# Build website in _site during development
destination: "./_site"

future: true

# Site settings
title: Divya Akula
subtitle: "a blog about programming, gaming, technology, ..."
email: akula.divya@gmail.com
name: Divya Akula
description: "A blog about M365 , Powerplatform and more."
appleicon_57: "/assets/icons/apple-icon-57x57.png"
appleicon_60: "/assets/icons/apple-icon-60x60.png"
appleicon_72: "/assets/icons/apple-icon-72x72.png"
appleicon_76: "/assets/icons/apple-icon-76x76.png"
appleicon_114: "/assets/icons/apple-icon-114x114.png"
appleicon_120: "/assets/icons/apple-icon-120x120.png"
appleicon_144: "/assets/icons/apple-icon-144x144.png"
appleicon_152: "/assets/icons/apple-icon-152x152.png"
appleicon_180: "/assets/icons/apple-icon-180x180.png"
androidicon_192: "/assets/icons/android-icon-192x192.png"
favicon_32: "/assets/icons/favicon-32x32.png"
favicon_96: "/assets/icons/favicon-96x96.png"
favicon_16: "/assets/icons/sfavicon-16x16.png"
assets_path:"/assets"
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
cover: "/assets/header_image.webp"
logo: "/assets/icons/assets/divya-akula-logo-gold.png"
sticker: "/assets/divya-akula-web-pic.png"
sticker-1_5x: "/assets/divya-akula-web-pic.png"
sticker-2x: "/assets/divya-akula-web-pic.png"

# Build settings
markdown: kramdown
inter_post_navigation: true
highlightjs_theme: "mono-blue"

# Pagination Settings
# https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
pagination:
  enabled: true
  per_page: 7
  permalink: "/page/:num/"
  sort_reverse: true

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
    - year
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'
    year: '/year/:year/'
  cover: "/assets/images/headers/gameboyzero.jpg"

thumbnail:
    resize_dimensions: '430x288^'
    crop_dimensions: '430x288+0+0'
    width: '430'
    height: '288'

gallery_items:
    resize_dimensions: '430x288^'
    crop_dimensions: '430x288+0+0'

# Buy me a Coffee username
buy_me_a_coffee_username: "divyaakula"

# Category descriptions (for archive pages)
descriptions:
  - cat: OpenAI
    desc: "Everything and anything related to Azure OpenAI, ..."

  - cat: PowerPlatform
    desc: "Only power platform no non sense ..."

  - cat: diy
    desc: "Not sure what I wanted to add hee"

  - cat: biology
    desc: "The world away from the computer screen"

  - cat: general
    desc: "Things about me which might interest you"

# Social icons and sharing options
social:
  - name: Twitter
    icon: twitter
    username: _divyaakula
    url: https://twitter.com/_divyaakula
    desc: Follow me on Twitter
    share: true

   - name: GitHub
    icon: github
    username: divya-akula
    url: https://github.com/divya-akula
    desc: Fork me on GitHub
    share: false

  - name: GitHub
    icon: github
    username: sepro
    url: https://github.com/sepro
    desc: Fork me on GitHub
    share: false

  - name: Facebook
    icon: facebook
    desc: Share on Facebook
    share: true

  - name: LinkedIn
    icon: linkedin
    desc: Share on LinkedIn
    share: true

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/social_fb.jpg"
    fb_image_width: 1200
    fb_image_height: 630
    fb_image_type: "image/jpg"

    twitter_image: "/assets/social_fb.jpg"

    os_repo: "https://github.com/4dcu-be/4dcu.be"
    os_rcs_type: "git"
    os_src: "git@github.com:4dcu-be/4dcu.be.git"
